jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Spotted\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email
        #fos_userbundle:
        #    id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        public:
           pattern: ^/
           anonymous: true
           form_login:
                check_path: /{_locale}/login_check
                login_path: /{_locale}
           
        secured_area:
           provider: main
           pattern: ^/{_locale}/home/
           form_login:
               check_path: /{_locale}/login_check
               login_path: /{_locale}
           logout:
               path : /{_locale}/logout
               target : /{_locale}
           remember_me:
              key:      aSecretKey
              lifetime: 3600
              path:     /home/
              domain:   ~ # Defaults to the current domain from $_SERVER 

        #main:
        #    pattern:        ^/home/*
        #    anonymous:      ~
        #    provider:       main
        #    form_login:
        #        login_path: fos_user_security_login
        #        check_path: fos_user_security_check
        #        default_target_path: fos_user_profile
        #    logout:
        #        path:       fos_user_security_logout
        #        target:     fos_user_security_login
        #    remember_me:
        #        key:        %secret% # %secret% est un parametre de parameters.yml

    access_control:
        - { path: ^/[a-z]+/home, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
