parameters:
#    spotted_spots.example.class: Spotted\SpotsBundle\Example

services:
#    spotted_spots.example:
#        class: %spotted_spots.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
