parameters:
#    spotted_user.example.class: Spotted\UserBundle\Example

services:
#    spotted_user.example:
#        class: %spotted_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
